version: '3.8'

services:
  resume-generator:
    build: .
    container_name: resume-generator
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
